"""Initial migration

Revision ID: aa73f59335e0
Revises: 
Create Date: 2026-02-06 21:08:56.213316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa73f59335e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('contact_emails', sa.JSON(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_country'), 'companies', ['country'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('fair_exhibitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fair_name', sa.String(length=200), nullable=False),
    sa.Column('fair_location', sa.String(length=200), nullable=True),
    sa.Column('fair_date', sa.Date(), nullable=True),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('booth_number', sa.String(length=50), nullable=True),
    sa.Column('hall', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('product_categories', sa.JSON(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('matched_keywords', sa.JSON(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fair_exhibitors_company_name'), 'fair_exhibitors', ['company_name'], unique=False)
    op.create_index(op.f('ix_fair_exhibitors_country'), 'fair_exhibitors', ['country'], unique=False)
    op.create_index(op.f('ix_fair_exhibitors_fair_date'), 'fair_exhibitors', ['fair_date'], unique=False)
    op.create_index(op.f('ix_fair_exhibitors_fair_name'), 'fair_exhibitors', ['fair_name'], unique=False)
    op.create_index(op.f('ix_fair_exhibitors_id'), 'fair_exhibitors', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gtip_code', sa.String(length=20), nullable=True),
    sa.Column('oem_code', sa.String(length=100), nullable=True),
    sa.Column('descriptions', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('subcategory', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_gtip_code'), 'products', ['gtip_code'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_oem_code'), 'products', ['oem_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=True),
    sa.Column('query_credits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('email_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('target_company_ids', sa.JSON(), nullable=True),
    sa.Column('target_filters', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('opened_count', sa.Integer(), nullable=True),
    sa.Column('clicked_count', sa.Integer(), nullable=True),
    sa.Column('bounced_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'COMPLETED', 'PAUSED', name='campaignstatus'), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_campaigns_id'), 'email_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_email_campaigns_status'), 'email_campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_email_campaigns_user_id'), 'email_campaigns', ['user_id'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query_type', sa.Enum('PRODUCT_SEARCH', 'COMPANY_SEARCH', 'MAP_SCRAPING', 'FAIR_SEARCH', 'IMAGE_SEARCH', name='querytype'), nullable=False),
    sa.Column('query_parameters', sa.JSON(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('results_data', sa.JSON(), nullable=True),
    sa.Column('credits_used', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_id'), 'search_queries', ['id'], unique=False)
    op.create_index(op.f('ix_search_queries_query_type'), 'search_queries', ['query_type'], unique=False)
    op.create_index(op.f('ix_search_queries_user_id'), 'search_queries', ['user_id'], unique=False)
    op.create_table('visitor_identifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referer', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_source', sa.String(length=50), nullable=True),
    sa.Column('identified_company_id', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('browser_fingerprint', sa.String(length=200), nullable=True),
    sa.Column('location_permission_granted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['identified_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_identifications_id'), 'visitor_identifications', ['id'], unique=False)
    op.create_index(op.f('ix_visitor_identifications_identified_company_id'), 'visitor_identifications', ['identified_company_id'], unique=False)
    op.create_index(op.f('ix_visitor_identifications_ip_address'), 'visitor_identifications', ['ip_address'], unique=False)
    op.create_index(op.f('ix_visitor_identifications_session_id'), 'visitor_identifications', ['session_id'], unique=True)
    op.create_table('campaign_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('personalized_subject', sa.String(length=500), nullable=True),
    sa.Column('personalized_body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bounced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('is_opened', sa.Boolean(), nullable=True),
    sa.Column('is_clicked', sa.Boolean(), nullable=True),
    sa.Column('is_bounced', sa.Boolean(), nullable=True),
    sa.Column('tracking_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_emails_campaign_id'), 'campaign_emails', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_emails_company_id'), 'campaign_emails', ['company_id'], unique=False)
    op.create_index(op.f('ix_campaign_emails_id'), 'campaign_emails', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_emails_tracking_id'), 'campaign_emails', ['tracking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_emails_tracking_id'), table_name='campaign_emails')
    op.drop_index(op.f('ix_campaign_emails_id'), table_name='campaign_emails')
    op.drop_index(op.f('ix_campaign_emails_company_id'), table_name='campaign_emails')
    op.drop_index(op.f('ix_campaign_emails_campaign_id'), table_name='campaign_emails')
    op.drop_table('campaign_emails')
    op.drop_index(op.f('ix_visitor_identifications_session_id'), table_name='visitor_identifications')
    op.drop_index(op.f('ix_visitor_identifications_ip_address'), table_name='visitor_identifications')
    op.drop_index(op.f('ix_visitor_identifications_identified_company_id'), table_name='visitor_identifications')
    op.drop_index(op.f('ix_visitor_identifications_id'), table_name='visitor_identifications')
    op.drop_table('visitor_identifications')
    op.drop_index(op.f('ix_search_queries_user_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_query_type'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_id'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_email_campaigns_user_id'), table_name='email_campaigns')
    op.drop_index(op.f('ix_email_campaigns_status'), table_name='email_campaigns')
    op.drop_index(op.f('ix_email_campaigns_id'), table_name='email_campaigns')
    op.drop_table('email_campaigns')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_oem_code'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_gtip_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_fair_exhibitors_id'), table_name='fair_exhibitors')
    op.drop_index(op.f('ix_fair_exhibitors_fair_name'), table_name='fair_exhibitors')
    op.drop_index(op.f('ix_fair_exhibitors_fair_date'), table_name='fair_exhibitors')
    op.drop_index(op.f('ix_fair_exhibitors_country'), table_name='fair_exhibitors')
    op.drop_index(op.f('ix_fair_exhibitors_company_name'), table_name='fair_exhibitors')
    op.drop_table('fair_exhibitors')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_country'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
